version: '3'                                                                    #
services:                                                                       #

  database:
    container_name: database                                                    # container 이름 설정
    build: ./database                                                           # dockerfile이 있는 위치
    ports:                                                                      # 내부에서 개방할 포트 : 외부에서 접근할 포트
      - "3306:3306"                                                             #

  backend:
    container_name: backend                                                     # container 이름 설정
    build: ./backend                                                            # dockerfile이 있는 위치
    volumes:                                                                    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
      - ./backend:/usr/src/app                                                  #
    ports:                                                                      # 내부에서 개방할 포트 : 외부에서 접근할 포트
      - "5000:5000"                                                             #
    environment:                                                                # 환경변수 설정
      - DBHOST=database                                                         #

  frontend:
    container_name: frontend                                                    # container 이름 설정
    build: ./frontend                                                           # dockerfile이 있는 위치
    volumes:                                                                    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
      - ./frontend:/home/node/app                                               #
    ports:                                                                      # 내부에서 개방할 포트 : 외부에서 접근할 포트
      - "8080:8080"                                                             #

# ■컨테이너생성 & 실행 명령어
# docker-compose
# docker-compose build
# docker-compose up -d

